// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZkfKD2KNM5m6gLUzEKc2gYp-ow6fz-Ak',
    appId: '1:1083314943715:web:c97e0538109ec231c937d6',
    messagingSenderId: '1083314943715',
    projectId: 'sign-8ed34',
    authDomain: 'sign-8ed34.firebaseapp.com',
    storageBucket: 'sign-8ed34.appspot.com',
    measurementId: 'G-JPGKRWF08J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzfIHqZAZXLjW2SBh5TrXW65-f7KJ22K0',
    appId: '1:1083314943715:android:b50d85486080411fc937d6',
    messagingSenderId: '1083314943715',
    projectId: 'sign-8ed34',
    storageBucket: 'sign-8ed34.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaJrTPpIqH7wF-9JJQWfrhRcUbZrr7AMY',
    appId: '1:1083314943715:ios:209b6f56a92a82a2c937d6',
    messagingSenderId: '1083314943715',
    projectId: 'sign-8ed34',
    storageBucket: 'sign-8ed34.appspot.com',
    androidClientId: '1083314943715-kk6nljsur38jne2ean8c6fon9ve9nh89.apps.googleusercontent.com',
    iosClientId: '1083314943715-bckhsrvs4spt5561s9kbp5lq4v5lg3bb.apps.googleusercontent.com',
    iosBundleId: 'com.example.currencyConverter',
  );
}
